# Generated by Django 4.2.11 on 2026-03-19 22:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "buyer_type",
                    models.CharField(
                        choices=[
                            ("factory", "Food Factory"),
                            ("distributor", "Distributor"),
                            ("retailer", "Retailer"),
                            ("individual", "Individual"),
                            ("exporter", "Exporter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "avg_monthly_orders",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit", "Credit Transfer"),
                            ("prepay", "Prepayment"),
                            ("escrow", "Smart Contract Escrow"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "annual_purchase_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain wallet for payments",
                        max_length=255,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("verified", models.BooleanField(default=False)),
                ("documents", models.FileField(blank=True, upload_to="buyer_docs/")),
                (
                    "rating",
                    models.FloatField(
                        default=5.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("total_purchases", models.IntegerField(default=0)),
                ("successful_deliveries", models.IntegerField(default=0)),
                ("dispute_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "-created_at"],
            },
        ),
    ]
