# Generated by Django 4.2.11 on 2026-03-19 22:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("country", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "farm_size_hectares",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "certification",
                    models.CharField(
                        choices=[
                            ("organic", "Organic Certified"),
                            ("fair_trade", "Fair Trade Certified"),
                            ("conventional", "Conventional"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "years_in_business",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "daily_production_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "max_order_size_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "min_order_size_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("account_holder", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                (
                    "wallet_address",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain wallet address for smart contract",
                        max_length=255,
                    ),
                ),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        help_text="Certificates, licenses, etc.",
                        upload_to="farmer_docs/",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=5.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                ("on_time_delivery_rate", models.FloatField(default=100.0)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "daily_capacity_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("year_round_available", models.BooleanField(default=False)),
                ("harvest_season_start", models.DateField(blank=True, null=True)),
                ("harvest_season_end", models.DateField(blank=True, null=True)),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[("A", "Grade A"), ("B", "Grade B"), ("C", "Grade C")],
                        default="A",
                        max_length=10,
                    ),
                ),
                ("price_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_products",
                        to="farmers.farmer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
