# Generated by Django 4.2.11 on 2026-03-19 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmproduct",
            name="available_quantity_kg",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="farmproduct",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="farmproduct",
            name="product_category",
            field=models.CharField(
                choices=[("vegetable", "Vegetable"), ("fruit", "Fruit")],
                default="vegetable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="farmproduct",
            name="product_photo",
            field=models.ImageField(blank=True, null=True, upload_to="product_photos/"),
        ),
        migrations.AddField(
            model_name="farmproduct",
            name="quality_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="product_certificates/"
            ),
        ),
    ]
