# Generated by Django 4.2.11 on 2026-03-19 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Awaiting Payment"),
                            ("escrow_locked", "Escrow Locked - Payment Received"),
                            ("processing", "Processing - Quality Check"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed - Payment Released"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "smart_contract_id",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain transaction hash",
                        max_length=255,
                    ),
                ),
                (
                    "smart_contract_address",
                    models.CharField(blank=True, max_length=255),
                ),
                ("expected_delivery_date", models.DateField()),
                ("shipping_address", models.TextField()),
                ("tracking_number", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payment_received_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "aggregated_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="products.aggregatedproductpool",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="buyers.buyer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("order_payment", "Order Payment"),
                            ("refund", "Refund"),
                            ("settlement", "Farmer Settlement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("transaction_hash", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending_confirmation", "Pending Blockchain Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("blockchain_timestamp", models.DateTimeField(blank=True, null=True)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initiated_by",
                    models.CharField(
                        choices=[("buyer", "Buyer"), ("farmer", "Farmer")],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("quality", "Quality Issue"),
                            ("quantity_short", "Quantity Shortage"),
                            ("late_delivery", "Late Delivery"),
                            ("non_delivery", "Non-Delivery"),
                            ("payment_issue", "Payment Issue"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "evidence",
                    models.FileField(blank=True, upload_to="dispute_evidence/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated to Admin"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("proposed_resolution", models.TextField(blank=True)),
                ("final_resolution", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
