# Generated by Django 4.2.11 on 2026-03-19 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSManagedBlockchainConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network_name", models.CharField(max_length=255, unique=True)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("HYPERLEDGER_FABRIC", "Hyperledger Fabric"),
                            ("ETHEREUM", "Ethereum"),
                        ],
                        max_length=50,
                    ),
                ),
                ("network_id", models.CharField(max_length=255)),
                ("member_id", models.CharField(max_length=255)),
                ("rpc_endpoint", models.CharField(max_length=255)),
                ("rpc_username", models.CharField(blank=True, max_length=255)),
                ("rpc_password", models.CharField(blank=True, max_length=255)),
                ("access_key", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("region", models.CharField(default="us-east-1", max_length=50)),
                ("smart_contract_arn", models.CharField(blank=True, max_length=255)),
                (
                    "contract_deployed_address",
                    models.CharField(blank=True, max_length=255),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "AWS Managed Blockchain Configs",
            },
        ),
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("order_escrow", "Order Escrow"),
                            ("bulk_aggregation", "Bulk Aggregation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("deployed", "Deployed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="deployed",
                        max_length=20,
                    ),
                ),
                ("contract_address", models.CharField(max_length=255, unique=True)),
                (
                    "network",
                    models.CharField(default="AWS_MANAGED_BLOCKCHAIN", max_length=50),
                ),
                ("chain_id", models.IntegerField(default=1)),
                ("buyer_wallet", models.CharField(max_length=255)),
                (
                    "seller_wallets",
                    models.JSONField(
                        default=list, help_text="List of farmer wallet addresses"
                    ),
                ),
                (
                    "escrow_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("delivery_deadline", models.DateTimeField()),
                ("dispute_period_days", models.IntegerField(default=30)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("deployment_tx_hash", models.CharField(blank=True, max_length=255)),
                ("activation_tx_hash", models.CharField(blank=True, max_length=255)),
                ("completion_tx_hash", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_contract",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Contract Created"),
                            ("funded", "Escrow Funded"),
                            ("payment_released", "Payment Released"),
                            ("refund_initiated", "Refund Initiated"),
                            ("dispute_filed", "Dispute Filed"),
                            ("dispute_resolved", "Dispute Resolved"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_hash", models.CharField(max_length=255, unique=True)),
                ("data", models.JSONField()),
                ("block_number", models.BigIntegerField()),
                ("transaction_hash", models.CharField(max_length=255)),
                ("log_index", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="smartcontracts.smartcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
