# Generated by Django 4.2.11 on 2026-03-19 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedProductPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "total_available_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "target_quantity_kg",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "average_price_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("platform_fee_percentage", models.FloatField(default=2.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open - Accepting Orders"),
                            ("active", "Active - Fulfilling Order"),
                            ("closed", "Closed - Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_products",
                    models.ManyToManyField(
                        related_name="aggregated_pools", to="farmers.farmproduct"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityAssurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Inspection"),
                            ("inspected", "Inspected & Passed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("inspector_name", models.CharField(blank=True, max_length=255)),
                ("inspection_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "certificate",
                    models.FileField(blank=True, upload_to="qa_certificates/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_assurance",
                        to="products.aggregatedproductpool",
                    ),
                ),
            ],
        ),
    ]
